name: My First Workflow
on:
  push:
    branches:
     -main
jobs:
 myFirstJob:
  runs-on: ubuntu-latest
  steps:
   -name: My First Step
    run: printenv
   -name: My Second Command
    echo "Amigoscode"
    echo "Hello" > file.txt
    ls
