name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  myFirstJob:
    runs-on: windows-latest

    steps:
      - name: My First Step
        run: |
          Get-ChildItem Env:

      - name: My Second Command
        run: |
          Write-Output "Amigoscode"
          "Hello" | Out-File -FilePath file.txt
          Get-ChildItem
      - name: Sleep Step
        run: sleep 20
