name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  myFirstJob:
    runs-on: windows-latest

    steps:
      - name: My First Step
        run: |
          Get-ChildItem Env:

      - name: My Second Step
        run: |
          Write-Output "Amigoscode"
          "Hello" | Out-File -FilePath file.txt
          Get-ChildItem
          Get-Content file.txt
      - name: Sleep Step
        run: sleep 5
      - name: My First Action
        uses: actions/checkout@v6
      - name: ls repo
        run: |
          Get-ChildItem
